run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - staticcheck
    - unused

linter-settings:
  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 15
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - CommentFormatting
  gosec:
    excludes:
      - G104 # Binding to all interfaces
  staticcheck:
    checks: ["SA1*", "SA2*", "SA3*", "SA4*", "SA5*"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocritic
