package sync

import (
	"fmt"
	"strings"

	"github.com/ccasJay/apimgr/config/models"
	"github.com/ccasJay/apimgr/internal/utils"
)

// GenerateEnvScript generates environment variable script content
func GenerateEnvScript(cfg *models.APIConfig) string {
	var buf strings.Builder

	// Add comments
	buf.WriteString("# Auto-generated active configuration - updated on each config change\n")
	buf.WriteString("# Do not edit this file manually\n\n")

	// Clear old environment variables
	buf.WriteString("# Clear previously set environment variables\n")
	buf.WriteString("unset ANTHROPIC_API_KEY\n")
	buf.WriteString("unset ANTHROPIC_AUTH_TOKEN\n")
	buf.WriteString("unset ANTHROPIC_BASE_URL\n")
	buf.WriteString("unset ANTHROPIC_MODEL\n")
	buf.WriteString("unset APIMGR_ACTIVE\n\n")

	// Set new environment variables
	buf.WriteString("# Set new environment variables\n")
	if cfg.APIKey != "" {
		buf.WriteString(fmt.Sprintf("export ANTHROPIC_API_KEY=%s\n", utils.ShellQuote(cfg.APIKey)))
	} else if cfg.AuthToken != "" {
		buf.WriteString(fmt.Sprintf("export ANTHROPIC_AUTH_TOKEN=%s\n", utils.ShellQuote(cfg.AuthToken)))
	}
	if cfg.BaseURL != "" {
		buf.WriteString(fmt.Sprintf("export ANTHROPIC_BASE_URL=%s\n", utils.ShellQuote(cfg.BaseURL)))
	}
	if cfg.Model != "" {
		buf.WriteString(fmt.Sprintf("export ANTHROPIC_MODEL=%s\n", utils.ShellQuote(cfg.Model)))
	}
	buf.WriteString(fmt.Sprintf("export APIMGR_ACTIVE=%s\n", utils.ShellQuote(cfg.Alias)))

	return buf.String()
}
